name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydatabase

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build Laravel
        run: |
          cd server
          cp .env.example .env
          composer install --prefer-dist --no-ansi --no-interaction --no-scripts --no-progress --no-suggest
          php artisan key:generate

      - name: Build React
        run: |
          cd client
          npm install
          npm run build
